# Generated by Django 5.0.3 on 2024-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meat_detection')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('result_class', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
