# Generated by Django 4.2.9 on 2024-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meatdetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomponent',
            name='name',
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='image',
            field=models.ImageField(default='', upload_to='product component detecions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='result_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meatdetection',
            name='image',
            field=models.ImageField(default='', upload_to='meat_detection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
