# Generated by Django 4.2.9 on 2024-06-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productcomponent_name_productcomponent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomponent',
            name='nutriations',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
