# Generated by Django 4.2.9 on 2024-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productcomponent_nutriations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='nutriations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
