# Generated by Django 4.2.9 on 2024-06-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productcomponent_nutriations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomponent',
            old_name='nutriations',
            new_name='nutritions',
        ),
    ]
