# Generated by Django 5.0.4 on 2024-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chronicdiseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chronic_disease',
        ),
        migrations.AddField(
            model_name='customuser',
            name='chronic_disease',
            field=models.ManyToManyField(to='accounts.chronicdiseases'),
        ),
    ]
