# Generated by Django 5.0.4 on 2024-04-29 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_chronic_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='chronic_disease',
        ),
        migrations.AddField(
            model_name='chronicdiseases',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_chronic_disease', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
