# Generated by Django 5.0.4 on 2024-05-01 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_allergy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea_food', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
