# Generated by Django 4.2.9 on 2024-06-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicdiseases',
            name='sugars',
            field=models.BooleanField(default=False),
        ),
    ]
