# Generated by Django 4.2.9 on 2024-06-28 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_chronicdiseases_sugars'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gluten', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy_nutrients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_carbohydrates', models.BooleanField(default=False)),
                ('total_sugars', models.BooleanField(default=False)),
                ('added_sugars', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diabetes_nutrients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HypertensionNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodium', models.BooleanField(default=False)),
                ('total_fat', models.BooleanField(default=False)),
                ('saturated_fat', models.BooleanField(default=False)),
                ('trans_fat', models.BooleanField(default=False)),
                ('cholesterol', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hypertension_nutrients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chronicdiseases',
            name='user',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='ChronicDiseases',
        ),
    ]
