# Generated by Django 4.2.9 on 2024-07-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_allergynutrients_diabetesnutrients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetesnutrients',
            old_name='added_sugars',
            new_name='Diabetes',
        ),
        migrations.RenameField(
            model_name='hypertensionnutrients',
            old_name='cholesterol',
            new_name='hypertension',
        ),
        migrations.RemoveField(
            model_name='diabetesnutrients',
            name='total_carbohydrates',
        ),
        migrations.RemoveField(
            model_name='diabetesnutrients',
            name='total_sugars',
        ),
        migrations.RemoveField(
            model_name='hypertensionnutrients',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='hypertensionnutrients',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='hypertensionnutrients',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='hypertensionnutrients',
            name='trans_fat',
        ),
    ]
