# Generated by Django 4.2.9 on 2024-07-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_diabetes_diabetesnutrients_diabetes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetesnutrients',
            old_name='diabetes',
            new_name='added_sugars',
        ),
        migrations.RenameField(
            model_name='hypertensionnutrients',
            old_name='hypertension',
            new_name='cholesterol',
        ),
        migrations.AddField(
            model_name='diabetesnutrients',
            name='total_carbohydrates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diabetesnutrients',
            name='total_sugars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hypertensionnutrients',
            name='saturated_fat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hypertensionnutrients',
            name='sodium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hypertensionnutrients',
            name='total_fat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hypertensionnutrients',
            name='trans_fat',
            field=models.BooleanField(default=False),
        ),
    ]
